# Generated by Django 5.2.9 on 2026-01-14 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscripciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('transferencia', 'Transferencia'), ('pago_movil', 'Pago Móvil')], max_length=30)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('captura_comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to=settings.AUTH_USER_MODEL)),
                ('inscripcion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='inscripciones.inscripcion')),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_verificados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
