# Generated by Django 5.2.9 on 2026-01-02 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscripciones', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('transferencia', 'Transferencia'), ('pago_movil', 'Pago Móvil')], max_length=30)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('captura_comprobante', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], max_length=20)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='inscripciones.inscripcion')),
                ('verificado_por', models.ForeignKey(blank=True, limit_choices_to={'rol': 'admin_pagos'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_verificados', to='usuarios.usuario')),
            ],
        ),
    ]
