# Generated by Django 5.2.9 on 2026-01-10 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
        ('usuarios', '0002_useractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='verificado_por',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'AdminP'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_verificados', to='usuarios.usuario'),
        ),
    ]
