# Generated by Django 5.2.9 on 2026-01-02 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion_breve', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.CharField(blank=True, max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cupos', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('borrador', 'Borrador')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('profesor', models.ForeignKey(limit_choices_to={'rol': 'profesor'}, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('orden', models.PositiveIntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='cursos.curso')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
