# Generated by Django 5.2.9 on 2026-01-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('cedula', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('rol', models.CharField(choices=[('AdminP', 'Administrador de Pagos'), ('AdminC', 'Administrador de Cursos'), ('profesor', 'Profesor'), ('estudiante', 'Estudiante')], max_length=30)),
                ('password', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
