# Generated by Django 5.2.9 on 2026-01-14 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField()),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='cursos.modulo')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RecursoLeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('archivo', 'Archivo'), ('enlace', 'Enlace')], max_length=30)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='recursos/')),
                ('url_enlace', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('orden', models.PositiveIntegerField()),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='lecciones.leccion')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
