# Generated by Django 5.2.9 on 2026-01-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recursoleccion',
            old_name='url_archivo',
            new_name='url_enlace',
        ),
        migrations.AddField(
            model_name='recursoleccion',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='recursos/'),
        ),
    ]
